### ISSUE TITLE
How to deploy?

### ISSUE THREAD

**Issue by ulamnet** [chunyenHuang/trand#56]
Hello , again me :) 

How to deploy to heroku this project?

thanks.

**Comment by chunyenHuang** [comment]
Hello~
This can help.
https://devcenter.heroku.com/articles/getting-started-with-nodejs#introduction

**Comment by ulamnet** [comment]
https://trandapp.herokuapp.com/ ı get application error.

**Comment by ulamnet** [comment]
2016-05-27T22:16:23.406005+00:00 app[web.1]:     at Object.<anonymous> (/app/app.js:19:10)
2016-05-27T22:16:23.406004+00:00 app[web.1]:     at Module.require (module.js:367:17)
2016-05-27T22:16:24.133887+00:00 heroku[web.1]: Process exited with status 1
2016-05-27T22:16:24.152532+00:00 heroku[web.1]: State changed from starting to crashed
2016-05-27T22:16:25.369545+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=trandapp.herokuapp.com request_id=ff6363d6-a3bd-4ee4-a39f-51f15b8429c8 fwd="176.240.155.135" dyno= connect= service= status=503 bytes=
2016-05-27T22:16:26.500628+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=trandapp.herokuapp.com request_id=60959398-d7fd-4b0e-a712-997375a9fad2 fwd="176.240.155.135" dyno= connect= service= status=503 bytes=
2016-05-27T22:16:58.476579+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=trandapp.herokuapp.com request_id=545e4f3e-a31a-43eb-9b82-0e81bc7f7521 fwd="176.240.155.135" dyno= connect= service= status=503 bytes=
2016-05-27T22:19:13.194520+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=trandapp.herokuapp.com request_id=b881e9c8-ea7b-45c6-996f-ab5b6f15a766 fwd="24.250.80.230" dyno= connect= service= status=503 bytes=
2016-05-27T22:19:13.805111+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=trandapp.herokuapp.com request_id=a8935366-

**Comment by chunyenHuang** [comment]
Since the original codes using AWS and FB login API.
You might need to check the following things:
1. Heroku dyno setup
 `$ heroku ps:scale web=1`  
2. Heroku config for AWS and FB
[AWS config](https://devcenter.heroku.com/articles/s3), [FB developer](https://developers.facebook.com/)
